version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5438:5432"

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local